import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase-server";

type EventRow={id:string;event_type:string;summary:string;evidence:Record<string,unknown>;status:string;created_at:string;priority:string|null;category:string|null;action_type:string|null;due_at:string|null;resolved_at:string|null};
function label(v:string|null|undefined){return (v||"general").replace(/[._-]+/g," ").replace(/\b\w/g,c=>c.toUpperCase());}
function dayKey(v:string){return new Date(v).toLocaleDateString(undefined,{year:"numeric",month:"long",day:"numeric"});}
function EventRowView({event}:{event:EventRow}){return <div className="relative pl-7 pb-7 last:pb-0"><span className="absolute left-0 top-1.5 h-2.5 w-2.5 rounded-full bg-vault ring-4 ring-ledger"/><div className="bg-white border border-rule p-4"><div className="flex flex-wrap items-center gap-2 mb-2"><span className="text-xs text-vault">{label(event.category)}</span><span className="text-xs text-ink/30">·</span><span className="text-xs text-ink/40">{label(event.event_type)}</span>{event.status==="auto_handled"&&<span className="text-[11px] px-2 py-0.5 bg-mist text-vault">Handled</span>}{event.status==="needs_approval"&&<span className="text-[11px] px-2 py-0.5 bg-alert/10 text-alert">Approval</span>}</div><p className="text-sm text-ink leading-relaxed">{event.summary}</p><div className="mt-2 flex flex-wrap gap-3 text-xs text-ink/40"><span>{new Date(event.created_at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</span>{event.action_type&&<span>Action: {label(event.action_type)}</span>}{event.priority&&event.priority!=="normal"&&<span>Priority: {label(event.priority)}</span>}{event.due_at&&<span>Due: {new Date(event.due_at).toLocaleString()}</span>}</div></div></div>;}
export default async function ActivityPage(){const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");const {data:business}=await supabase.from("businesses").select("id,name").eq("owner_id",user.id).single();if(!business)redirect("/onboarding");const {data:events}=await supabase.from("events").select("id,event_type,summary,evidence,status,created_at,priority,category,action_type,due_at,resolved_at").eq("business_id",business.id).order("created_at",{ascending:false}).limit(500);const rows=(events??[]) as EventRow[];const groups=rows.reduce<Record<string,EventRow[]>>((acc,event)=>{const key=dayKey(event.created_at);(acc[key]??=[]).push(event);return acc;},{});return <main className="min-h-screen bg-ledger"><header className="border-b border-rule bg-white"><div className="max-w-5xl mx-auto px-4 sm:px-6 py-5 flex items-center justify-between"><div><Link href="/dashboard" className="text-xs text-ink/45 hover:text-ink">← Dashboard</Link><h1 className="font-display text-2xl text-ink mt-1">Business Timeline</h1></div><Link href="/dashboard/actions" className="text-sm text-vault hover:text-vaultDeep">Action Center</Link></div></header><section className="max-w-5xl mx-auto px-4 sm:px-6 py-8 sm:py-12"><div className="mb-10"><p className="text-xs uppercase tracking-[0.16em] text-vault font-medium mb-2">Source timeline</p><h2 className="font-display text-3xl text-ink">Everything that happened</h2><p className="text-sm text-ink/55 mt-2 max-w-2xl">The complete event history stays here. The Action Center deliberately shows only work, exceptions and decisions that deserve attention.</p></div>{!rows.length?<div className="bg-white border border-rule p-8 text-sm text-ink/45">No business events have been recorded yet.</div>:<div className="space-y-10">{Object.entries(groups).map(([day,dayEvents])=><section key={day}><h3 className="font-display text-lg text-ink mb-4">{day}</h3><div className="border-l border-rule ml-1.5 pl-4">{dayEvents.map(event=><EventRowView key={event.id} event={event}/>)}</div></section>)}</div>}</section></main>;}
