"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {createClient} from "@/lib/supabase-browser";
import {DEFAULT_INVOICE_SETTINGS,InvoiceSettings} from "@/lib/business-settings";
const labels:Record<keyof InvoiceSettings,string>={show_logo:"Business logo",show_customer_address:"Customer address",show_tax:"Tax line",show_discount:"Discount",show_shipping:"Shipping",show_reference:"Reference",show_purchase_order:"Purchase order",show_notes:"Customer note",show_terms:"Terms & conditions",show_product_image:"Product image",show_sku:"SKU",show_payment_details:"Payment details",show_signature:"Signature",show_qr_payment:"QR payment"};
export default function SettingsPage(){
 const supabase=createClient(); const [id,setId]=useState(""); const [taxMode,setTaxMode]=useState("auto"); const [rate,setRate]=useState(0); const [taxName,setTaxName]=useState(""); const [jurisdiction,setJurisdiction]=useState(""); const [invoice,setInvoice]=useState<InvoiceSettings>(DEFAULT_INVOICE_SETTINGS); const [saving,setSaving]=useState(false); const [saved,setSaved]=useState(false);
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data:b}=await supabase.from("businesses").select("id").eq("owner_id",user.id).single();if(!b)return;setId(b.id);let {data:s}=await supabase.from("business_settings").select("*").eq("business_id",b.id).maybeSingle();if(!s){await supabase.from("business_settings").insert({business_id:b.id});s=(await supabase.from("business_settings").select("*").eq("business_id",b.id).single()).data}if(s){setTaxMode(s.tax_mode);setRate(Number(s.default_tax_rate));setTaxName(s.default_tax_name||"");setJurisdiction(s.tax_jurisdiction||"");setInvoice({...DEFAULT_INVOICE_SETTINGS,...s.invoice_settings})}})()},[]);
 async function save(){setSaving(true);setSaved(false);const {error}=await supabase.from("business_settings").update({tax_mode:taxMode,default_tax_rate:rate,default_tax_name:taxName||null,tax_jurisdiction:jurisdiction||null,invoice_settings:invoice,updated_at:new Date().toISOString()}).eq("business_id",id);setSaving(false);setSaved(!error)}
 return <main className="min-h-screen bg-ledger"><header className="border-b border-rule bg-white"><div className="max-w-6xl mx-auto px-6 py-5 flex justify-between"><div><Link href="/dashboard" className="text-xs text-ink/45">← Dashboard</Link><h1 className="font-display text-2xl mt-1">Business settings</h1></div><div className="flex gap-4 text-sm"><Link href="/dashboard/money" className="text-vault">Money</Link><Link href="/dashboard/integrations" className="text-vault">Integrations</Link></div></div></header>
 <section className="max-w-4xl mx-auto px-6 py-10 space-y-6"><section className="bg-white border border-rule p-6"><h2 className="font-display text-xl">Tax configuration</h2><p className="text-sm text-ink/50 mt-1">Tax is configurable because not every transaction is taxable. Core invoice identity and totals remain mandatory.</p><div className="grid md:grid-cols-2 gap-4 mt-5"><label className="text-sm text-ink/60">Tax mode<select value={taxMode} onChange={e=>setTaxMode(e.target.value)} className="mt-1.5 w-full border border-rule px-3 py-2.5"><option value="auto">Use configured default</option><option value="manual">Manual per invoice</option><option value="disabled">Disabled by default</option></select></label><label className="text-sm text-ink/60">Default tax rate %<input type="number" min="0" step=".01" value={rate} onChange={e=>setRate(Number(e.target.value))} className="mt-1.5 w-full border border-rule px-3 py-2.5"/></label><label className="text-sm text-ink/60">Tax name<input value={taxName} onChange={e=>setTaxName(e.target.value)} placeholder="VAT / GST / Sales tax" className="mt-1.5 w-full border border-rule px-3 py-2.5"/></label><label className="text-sm text-ink/60">Tax jurisdiction<input value={jurisdiction} onChange={e=>setJurisdiction(e.target.value)} placeholder="Country / region" className="mt-1.5 w-full border border-rule px-3 py-2.5"/></label></div></section>
 <section className="bg-white border border-rule p-6"><h2 className="font-display text-xl">Invoice controls</h2><p className="text-sm text-ink/50 mt-1">Optional presentation features can be hidden without deleting their underlying data.</p><div className="grid sm:grid-cols-2 gap-3 mt-5">{(Object.keys(labels) as (keyof InvoiceSettings)[]).map(k=><label key={k} className="flex items-center justify-between border border-rule p-3 text-sm"><span>{labels[k]}</span><input type="checkbox" checked={invoice[k]} onChange={e=>setInvoice(v=>({...v,[k]:e.target.checked}))}/></label>)}</div></section>
 <div className="flex items-center justify-end gap-4"><span className="text-sm text-vault">{saved?"Saved.":""}</span><button onClick={save} disabled={saving||!id} className="bg-ink text-mist px-6 py-3 text-sm">{saving?"Saving…":"Save settings"}</button></div></section></main>
}