// @ts-nocheck
import Link from "next/link";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase-server";

async function createListing(formData:FormData){
 "use server"; const supabase=await createClient();
 const {data:{user}}=await supabase.auth.getUser(); if(!user)redirect("/login");
 const {data:business}=await supabase.from("businesses").select("id,currency").eq("owner_id",user.id).single(); if(!business)redirect("/onboarding");
 const {error}=await supabase.from("marketplace_listings").insert({seller_business_id:business.id,title:String(formData.get("title")||"").trim(),description:String(formData.get("description")||"").trim(),listing_type:String(formData.get("listingType")||"service"),category:String(formData.get("category")||"general"),price:formData.get("price")?Number(formData.get("price")):null,currency:String(formData.get("currency")||business.currency||"USD"),quantity_available:formData.get("quantity")?Number(formData.get("quantity")):null,status:"draft",tags:String(formData.get("tags")||"").split(",").map(v=>v.trim()).filter(Boolean),created_by:user.id});
 if(error)throw new Error(error.message); revalidatePath("/dashboard/marketplace");
}
async function publishListing(formData:FormData){
 "use server"; const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)redirect("/login"); const {data:business}=await supabase.from("businesses").select("id").eq("owner_id",user.id).single(); if(!business)redirect("/onboarding"); const id=String(formData.get("id")||"");
 await supabase.from("marketplace_listings").update({status:"published",updated_at:new Date().toISOString()}).eq("id",id).eq("seller_business_id",business.id); revalidatePath("/dashboard/marketplace");
}
async function inquire(formData:FormData){
 "use server"; const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)redirect("/login"); const {data:business}=await supabase.from("businesses").select("id").eq("owner_id",user.id).single(); if(!business)redirect("/onboarding"); const id=String(formData.get("listingId")||""); const message=String(formData.get("message")||"").trim();
 const {data:listing}=await supabase.from("marketplace_listings").select("id,seller_business_id,status").eq("id",id).eq("status","published").single();
 if(!listing||listing.seller_business_id===business.id)throw new Error("Listing unavailable for inquiry.");
 await supabase.from("marketplace_inquiries").insert({listing_id:id,buyer_business_id:business.id,message,requested_quantity:formData.get("quantity")?Number(formData.get("quantity")):null,offer_amount:formData.get("offer")?Number(formData.get("offer")):null,currency:formData.get("currency")||null});
 revalidatePath("/dashboard/marketplace");
}
export default async function MarketplacePage(){
 const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)redirect("/login");
 const {data:business}=await supabase.from("businesses").select("id,name,currency").eq("owner_id",user.id).single(); if(!business)redirect("/onboarding");
 const [{data:mine},{data:listings},{data:inquiries}]=await Promise.all([
  supabase.from("marketplace_listings").select("id,title,description,listing_type,category,price,currency,quantity_available,status,tags,created_at").eq("seller_business_id",business.id).order("created_at",{ascending:false}),
  supabase.from("marketplace_listings").select("id,title,description,listing_type,category,price,currency,quantity_available,seller_business_id,tags,created_at,seller:businesses(name)").eq("status","published").neq("seller_business_id",business.id).order("created_at",{ascending:false}).limit(50),
  supabase.from("marketplace_inquiries").select("id,listing_id,buyer_business_id,message,status,created_at,listing:marketplace_listings(title)").or("buyer_business_id.eq."+business.id).limit(50)
 ]);
 return <main className="min-h-screen bg-ledger"><header className="border-b border-rule bg-white"><div className="max-w-7xl mx-auto px-6 py-5 flex justify-between items-center"><div><Link href="/dashboard" className="text-xs text-ink/45">← Dashboard</Link><h1 className="font-display text-2xl mt-1">B2B Marketplace</h1></div><Link href="/dashboard/ai-builder" className="bg-ink text-white px-4 py-2 text-sm">AI Builder</Link></div></header>
 <section className="max-w-7xl mx-auto px-6 py-8"><div className="grid lg:grid-cols-[360px_1fr] gap-6">
 <form action={createListing} className="bg-white border border-rule p-5 h-fit"><p className="text-xs uppercase tracking-[.16em] text-vault">Seller tools</p><h2 className="font-display text-2xl mt-2">Create a listing</h2><input name="title" required placeholder="Listing title" className="mt-4 w-full border border-rule px-3 py-2.5 text-sm"/><textarea name="description" rows={5} placeholder="Description, business terms, delivery scope" className="mt-3 w-full border border-rule px-3 py-3 text-sm"/><div className="grid grid-cols-2 gap-2 mt-3"><select name="listingType" className="border border-rule px-3 py-2.5 text-sm"><option>service</option><option>product</option><option>wholesale</option><option>partnership</option><option>procurement</option></select><input name="category" placeholder="category" className="border border-rule px-3 py-2.5 text-sm"/></div><div className="grid grid-cols-2 gap-2 mt-3"><input name="price" type="number" step="0.01" placeholder="Price" className="border border-rule px-3 py-2.5 text-sm"/><input name="currency" defaultValue={business.currency||"USD"} className="border border-rule px-3 py-2.5 text-sm"/></div><div className="grid grid-cols-2 gap-2 mt-3"><input name="quantity" type="number" step="0.01" placeholder="Quantity" className="border border-rule px-3 py-2.5 text-sm"/><input name="tags" placeholder="tags, comma separated" className="border border-rule px-3 py-2.5 text-sm"/></div><button className="mt-4 w-full bg-vault text-white px-4 py-3 text-sm">Save draft listing</button></form>
 <div><section className="bg-white border border-rule p-5 mb-6"><p className="text-xs uppercase tracking-[.16em] text-vault">Discover</p><h2 className="font-display text-2xl mt-1">Published business listings</h2><div className="grid md:grid-cols-2 gap-4 mt-5">{(listings??[]).map(l=><div key={l.id} className="border border-rule p-4"><div className="text-[10px] uppercase text-vault">{l.listing_type} · {l.category}</div><h3 className="font-medium mt-1">{l.title}</h3><p className="text-sm text-ink/55 mt-2">{l.description}</p><p className="text-xs text-ink/40 mt-3">{l.seller?.name||"Business"} · {l.price!=null?(String(l.currency||"")+" "+Number(l.price).toLocaleString()):"Contact seller"}</p><form action={inquire} className="mt-4 space-y-2"><input type="hidden" name="listingId" value={l.id}/><textarea name="message" required rows={2} placeholder="Send a business inquiry" className="w-full border border-rule px-3 py-2 text-xs"/><div className="flex gap-2"><input name="quantity" type="number" step="0.01" placeholder="Qty" className="w-24 border border-rule px-2 py-2 text-xs"/><input name="offer" type="number" step="0.01" placeholder="Offer" className="w-24 border border-rule px-2 py-2 text-xs"/><button className="bg-ink text-white px-3 py-2 text-xs">Inquire</button></div></form></div>)}</div>{!(listings??[]).length&&<p className="mt-4 text-sm text-ink/45">No published listings yet.</p>}</section>
 <section className="bg-white border border-rule p-5"><h2 className="font-display text-xl">Your listings</h2><div className="mt-4 space-y-2">{(mine??[]).map(l=><div key={l.id} className="border border-rule p-4 flex justify-between gap-3 items-center"><div><p className="text-sm font-medium">{l.title}</p><p className="text-xs text-ink/45 mt-1 capitalize">{l.status} · {l.listing_type}</p></div>{l.status==="draft"&&<form action={publishListing}><input type="hidden" name="id" value={l.id}/><button className="bg-vault text-white px-3 py-2 text-xs">Publish</button></form>}</div>)}</div></section>
 </div></div></section></main>;
}