"use client";
import { useMemo, useState } from "react";

export default function MenuOrderClient({slug,currency,items}:{slug:string;currency:string;items:any[]}){
 const [cart,setCart]=useState<Record<string,number>>({});
 const [table,setTable]=useState("");
 const [notes,setNotes]=useState("");
 const [submitting,setSubmitting]=useState(false);
 const [result,setResult]=useState<any>(null);
 const total=useMemo(()=>items.reduce((sum:any,item:any)=>sum+(Number(item.price)||0)*(cart[item.id]||0),0),[items,cart]);
 function change(id:string,delta:number){setCart(prev=>{const next=Math.max(0,(prev[id]||0)+delta);const copy={...prev};if(next)copy[id]=next;else delete copy[id];return copy;});}
 async function submit(){const selected=Object.entries(cart).filter(([,q])=>q>0).map(([menuItemId,quantity])=>({menuItemId,quantity}));if(!selected.length)return;setSubmitting(true);setResult(null);const response=await fetch("/api/public/menu/"+slug+"/order",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:selected,tableLabel:table,notes})});const data=await response.json().catch(()=>({}));setSubmitting(false);setResult(response.ok?data:{error:data.error||"Order failed"});if(response.ok)setCart({});}
 return <div className="mt-7"><div className="space-y-3">{items.map(item=><div key={item.id} className="bg-white border border-rule p-4 flex justify-between gap-4"><div><h3 className="font-medium">{item.name}</h3>{item.description&&<p className="text-sm text-ink/55 mt-1">{item.description}</p>}<p className="text-xs text-ink/40 mt-2">{currency} {Number(item.price).toLocaleString()}</p></div><div className="flex items-center gap-2"><button onClick={()=>change(item.id,-1)} className="border border-rule w-8 h-8">−</button><span className="w-5 text-center text-sm">{cart[item.id]||0}</span><button onClick={()=>change(item.id,1)} className="border border-rule w-8 h-8">+</button></div></div>)}</div><div className="sticky bottom-0 bg-white/95 backdrop-blur border border-rule mt-6 p-4"><div className="grid sm:grid-cols-2 gap-2"><input value={table} onChange={e=>setTable(e.target.value)} placeholder="Table / pickup label" className="border border-rule px-3 py-2.5 text-sm"/><input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Order notes" className="border border-rule px-3 py-2.5 text-sm"/></div><div className="mt-3 flex items-center justify-between gap-4"><div><p className="text-xs text-ink/45">Total</p><p className="font-display text-xl">{currency} {total.toLocaleString()}</p></div><button disabled={submitting||total<=0} onClick={submit} className="bg-ink text-white px-5 py-3 text-sm disabled:opacity-40">{submitting?"Sending…":"Send to kitchen"}</button></div>{result&&<div className="mt-3 text-sm">{result.error?<span className="text-red-700">{result.error}</span>:<span className="text-vault">Order {result.order?.order_number} received. Kitchen status: {result.order?.status}.</span>}</div>}</div></div>;
}
