"use client";
import {useMemo,useState} from "react";
type C={name:string;cat:string;letter:string;connected:boolean;desc:string};
const cats=["All Connectors","Development","Productivity","Communication","Finance","Marketing","Storage","Analytics","Security","Other"];
const connectors:C[]=([
["GitHub","Development","G",false,"Repositories, commits, issues and pull requests."],["Vercel","Development","▲",true,"Deployments, previews, domains and build status."],["Supabase","Development","S",true,"Database, authentication and business data."],["Stripe","Finance","S",false,"Payments, customers and invoices."],["Google Drive","Storage","G",false,"Business files and shared knowledge."],["Slack","Communication","S",false,"Channels, messages and notifications."],["OpenAI","Development","AI",false,"Approved AI model access."],["Notion","Productivity","N",false,"Knowledge bases and operating notes."],["PayPal","Finance","P",false,"Payments and transaction context."],["QuickBooks","Finance","Q",false,"Accounting and financial reporting."],["Xero","Finance","X",false,"Accounting and financial reports."],["Figma","Productivity","F",false,"Design files and components."],["Linear","Productivity","L",false,"Issues, projects and cycles."],["Jira","Development","J",false,"Tickets, workflows and delivery context."],["Cloudflare","Security","C",false,"DNS, edge and security controls."],["AWS","Other","A",false,"Cloud infrastructure context."],["Firebase","Development","F",false,"Application backend services."],["Mailchimp","Marketing","M",false,"Audiences and campaigns."],["Twilio","Communication","T",false,"SMS and messaging workflows."],["Shopify","Finance","S",false,"Products, orders and customers."]
 ] as [string,string,string,boolean,string][]).map(x=>({name:x[0],cat:x[1],letter:x[2],connected:x[3],desc:x[4]}));
const appRows=[["GitHub","Connected"],["Vercel","Connected"],["Supabase","Connected"],["Stripe","Not connected"],["Google Drive","Not connected"],["Slack","Not connected"]];
const ext=[["Vercel","Deployments and preview infrastructure"],["Netlify","Web hosting and deployment"],["Cloudflare","DNS, edge and security"],["AWS","Cloud infrastructure"],["Google Cloud","Cloud services and data"],["Firebase","Application backend services"]];
export default function IntegrationsPage(){
 const [cat,setCat]=useState("All Connectors"),[search,setSearch]=useState(""),[selected,setSelected]=useState<C|null>(null),[tab,setTab]=useState("General");
 const filtered=useMemo(()=>connectors.filter(c=>(cat==="All Connectors"||c.cat===cat)&&(c.name.toLowerCase().includes(search.toLowerCase())||c.cat.toLowerCase().includes(search.toLowerCase()))),[cat,search]);
 return <div className="min-h-screen p-4 lg:p-6 relative"><div className="pointer-events-none absolute inset-x-0 top-0 h-80 bg-[radial-gradient(circle_at_45%_0%,rgba(37,99,235,.16),transparent_62%)]"/><div className="relative max-w-[1500px] mx-auto">
  <header className="mb-5 pb-4 border-b border-white/[.055]"><div className="text-[8px] uppercase tracking-[.2em] text-cyan-200/40">Section 4</div><h1 className="text-[20px] font-semibold text-white mt-1">Integrations, Apps &amp; Connectors</h1><p className="text-[10px] text-slate-500 mt-1">Connect your tools, apps and services. Build a more powerful business.</p></header>

  <section className="mb-5"><div className="flex justify-between items-end mb-2"><div><h2 className="text-[12px] font-semibold text-white">4.1 Connector Marketplace</h2><p className="text-[8px] text-white/25 mt-1">Find and connect services for your business.</p></div><span className="text-[8px] text-cyan-200/35">50+ CONNECTORS</span></div>
   <div className="grid lg:grid-cols-[155px_1fr] gap-2.5"><aside className="rounded-xl border border-white/[.06] bg-[#080f1b]/95 p-2">{cats.map(x=><button key={x} onClick={()=>setCat(x)} className={`w-full text-left px-2.5 py-2 rounded-lg text-[8px] ${cat===x?"text-white bg-indigo-500/15 border border-indigo-300/10":"text-white/30 hover:text-white/70"}`}>{x}{x==="All Connectors"&&<span className="float-right text-white/20">50+</span>}</button>)}</aside>
    <div><div className="relative mb-2"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search connectors, apps or services..." className="w-full bg-[#080f1b] border border-white/[.06] rounded-xl px-3 py-2.5 text-[9px] text-white placeholder:text-white/20 outline-none"/></div><div className="grid grid-cols-2 sm:grid-cols-3 xl:grid-cols-5 gap-2">{filtered.slice(0,10).map(c=><button key={c.name} onClick={()=>setSelected(c)} className="text-left rounded-xl border border-white/[.06] bg-[#0a1220]/90 p-3 hover:border-cyan-300/20"><div className="w-8 h-8 rounded-lg bg-white/[.04] border border-white/[.07] grid place-items-center text-white text-[11px] font-bold">{c.letter}</div><div className="text-[9px] text-white mt-2">{c.name}</div><div className="text-[7px] text-white/25">{c.cat}</div><div className={`text-[7px] mt-2 ${c.connected?"text-emerald-300/70":"text-indigo-200/45"}`}>{c.connected?"● Connected":"Configure →"}</div></button>)}</div></div>
   </div>
  </section>

  <div className="grid lg:grid-cols-2 gap-3 mb-5">
   <section className="rounded-xl border border-white/[.06] bg-[#0a1220]/90 overflow-hidden"><div className="p-3 border-b border-white/[.05] flex justify-between"><div><h2 className="text-[11px] font-semibold text-white">4.2 Connected Apps</h2><p className="text-[7px] text-white/25 mt-1">Connected services and access controls.</p></div><button className="text-[7px] text-indigo-200/70">+ Add New Connection</button></div>{appRows.map(([n,s])=><div key={n} className="px-3 py-2.5 flex justify-between border-b border-white/[.04]"><span className="text-[8px] text-white/55">{n}</span><span className={`text-[7px] ${s==="Connected"?"text-emerald-300":"text-white/25"}`}>{s}{s==="Connected"&&" · Revoke"}</span></div>)}</section>
   <section className="rounded-xl border border-white/[.06] bg-[#0a1220]/90 overflow-hidden"><div className="p-3 border-b border-white/[.05]"><h2 className="text-[11px] font-semibold text-white">4.3 Integration Settings</h2><div className="flex gap-1 mt-3">{["General","Webhooks","API Keys"].map(x=><button key={x} onClick={()=>setTab(x)} className={`px-2.5 py-1.5 rounded-lg text-[7px] ${tab===x?"text-white bg-indigo-500/15":"text-white/25"}`}>{x}</button>)}</div></div><div className="p-3 space-y-2">{tab==="General"?["Connection notifications","Allow AI context access","Require approval for write actions"].map(x=><div key={x} className="flex justify-between p-2.5 rounded-lg bg-white/[.018] border border-white/[.04] text-[8px] text-white/45">{x}<span className="w-7 h-3.5 rounded-full bg-emerald-500/70"/></div>):<div className="rounded-lg border border-white/[.05] p-3 text-[8px] text-white/30">{tab==="Webhooks"?"Webhook URL · invoice.created · payment.received · customer.updated · project.updated":"Scoped, revocable and audited API keys."}</div>}<button className="w-full py-2 rounded-lg bg-gradient-to-r from-blue-600 to-violet-600 text-[8px] text-white">Save Settings</button></div></section>
  </div>

  <div className="grid lg:grid-cols-2 gap-3 mb-5">
   <section className="rounded-xl border border-white/[.06] bg-[#0a1220]/90 p-3"><div className="flex justify-between mb-3"><div><h2 className="text-[11px] font-semibold text-white">4.4 App Catalog</h2><p className="text-[7px] text-white/25 mt-1">Installed, available and custom apps.</p></div><span className="text-[7px] text-white/20">Installed · Available · Custom</span></div><div className="grid grid-cols-2 gap-2">{["Website Builder","CRM","Inventory","Accounting","Email Marketing","HR & Payroll"].map((x,i)=><div key={x} className="rounded-lg border border-white/[.05] bg-white/[.018] p-2.5 flex justify-between text-[8px] text-white/45">{x}<span className={i===0?"text-emerald-300":"text-indigo-200/50"}>{i===0?"Installed":"Install"}</span></div>)}</div></section>
   <section className="rounded-xl border border-white/[.06] bg-[#0a1220]/90 p-3"><div className="flex justify-between mb-3"><div><h2 className="text-[11px] font-semibold text-white">4.5 Developer Tools</h2><p className="text-[7px] text-white/25 mt-1">API, SDKs, Webhooks and Docs.</p></div></div><div className="rounded-lg border border-white/[.05] bg-[#060b13] p-3 font-mono text-[7px] text-cyan-100/45">POST /api/v1/projects<br/>Authorization: Bearer &lt;scoped_key&gt;<br/>X-BizStack-Event: project.updated</div><div className="grid grid-cols-2 gap-2 mt-2">{["API Documentation","SDKs","Webhook Events","Postman Collection","Rate Limits","Authentication"].map(x=><button key={x} className="text-left rounded-lg border border-white/[.05] p-2 text-[7px] text-white/35">{x} <span className="float-right">→</span></button>)}</div></section>
  </div>

  <section><div className="flex justify-between items-end mb-2"><div><h2 className="text-[12px] font-semibold text-white">4.6 External Services</h2><p className="text-[8px] text-white/25 mt-1">Infrastructure providers BizStack can coordinate with.</p></div></div><div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-2">{ext.map(([n,d])=><div key={n} className="rounded-xl border border-white/[.06] bg-[#0a1220]/90 p-3"><div className="w-8 h-8 rounded-lg bg-white/[.04] border border-white/[.06] grid place-items-center text-white text-[9px]">{n[0]}</div><div className="text-[9px] text-white mt-2">{n}</div><div className="text-[7px] text-white/25 mt-1">{d}</div></div>)}</div></section>
  {selected&&<div className="fixed inset-0 z-50 bg-black/65 backdrop-blur-sm flex justify-end" onClick={()=>setSelected(null)}><aside onClick={e=>e.stopPropagation()} className="h-full w-full max-w-md bg-[#07101e] border-l border-cyan-300/10 p-5"><div className="flex justify-between"><div><div className="text-[7px] uppercase tracking-[.18em] text-cyan-200/40">{selected.cat}</div><h2 className="text-base font-semibold text-white mt-1">{selected.name}</h2><p className="text-[8px] text-white/30 mt-1">{selected.desc}</p></div><button onClick={()=>setSelected(null)} className="text-white/30 text-lg">×</button></div><div className="mt-5 rounded-xl border border-indigo-300/10 bg-indigo-500/[.045] p-4"><div className="text-[8px] text-indigo-200/45 uppercase tracking-[.16em]">Connection flow</div>{["Authenticate account","Review requested scopes","Test connection","Enable actions & events"].map((x,i)=><div key={x} className="flex gap-2 items-center mt-3 text-[8px] text-white/40"><span className="w-5 h-5 rounded-full border border-white/10 grid place-items-center">{i+1}</span>{x}</div>)}</div></aside></div>}
 </div></div>;
}
