"use client";
import { useState } from "react";

const MONTHS=["Jan","Feb","Mar","Apr","May","Jun","Jul"];
const REV=[180,140,300,200,280,160,240], EXP=[90,80,160,110,140,90,130], MAX=Math.max(...REV);
function toPath(data:number[],w:number,h:number){return data.map((v,i)=>`${(i/(data.length-1))*w},${h-(v/MAX)*h}`).join(" ");}
const DONUT=[{label:"Invoices",pct:45,color:"#5B6EF5"},{label:"Services",pct:25,color:"#8B5CF6"},{label:"Subscriptions",pct:20,color:"#22C55E"},{label:"Other",pct:10,color:"#F5A524"}];
function DonutChart(){const r=60,cx=80,cy=80,circ=2*Math.PI*r;let offset=0;return <svg viewBox="0 0 160 160" className="w-32 h-32">{DONUT.map(d=>{const dash=d.pct/100*circ,el=<circle key={d.label} cx={cx} cy={cy} r={r} fill="none" stroke={d.color} strokeWidth="20" strokeDasharray={`${dash} ${circ-dash}`} strokeDashoffset={-offset} style={{transform:"rotate(-90deg)",transformOrigin:`${cx}px ${cy}px`}}/>;offset+=dash;return el;})}<circle cx={cx} cy={cy} r="43" fill="#0b1220"/><text x={cx} y={cy+4} textAnchor="middle" fill="white" fontSize="13" fontWeight="bold">$24.5K</text></svg>;}
export default function ReportsPage(){
 const [tab,setTab]=useState("Overview"); const TABS=["Overview","Invoices","Customers","Products","Marketing"];
 return <div className="min-h-screen p-5 lg:p-6 relative"><div className="pointer-events-none absolute inset-x-0 top-0 h-72 bg-[radial-gradient(circle_at_48%_0%,rgba(37,99,235,.15),transparent_62%)]"/><div className="relative max-w-[1500px] mx-auto">
  <div className="flex flex-col lg:flex-row lg:items-end justify-between gap-4 mb-5 pb-5 border-b border-white/[.055]"><div><div className="flex items-center gap-2.5"><span className="w-9 h-9 rounded-xl bg-gradient-to-br from-indigo-400/20 to-cyan-400/10 border border-indigo-200/10 grid place-items-center text-indigo-100/80">▥</span><div><div className="text-[8px] uppercase tracking-[.2em] text-cyan-200/45">Business intelligence</div><h1 className="text-[20px] font-semibold tracking-[-.03em] text-white">Reports &amp; Analytics</h1></div></div><p className="text-[10px] text-slate-500 mt-2 ml-11">See financial, customer, product and growth signals in one governed workspace.</p></div><select className="bg-[#0a111e]/90 border border-white/[.065] text-slate-400 text-[9px] rounded-xl px-3 py-2.5 focus:outline-none focus:border-indigo-300/25"><option>This Month</option><option>Last Month</option><option>Last Quarter</option></select></div>
  <div className="flex gap-1 mb-5 bg-[#0a111e]/90 border border-white/[.06] rounded-xl p-1 w-fit overflow-x-auto">{TABS.map(t=><button key={t} onClick={()=>setTab(t)} className={`shrink-0 px-4 py-2 rounded-lg text-[9px] transition-all ${tab===t?"text-white bg-indigo-500/20 border border-indigo-300/15":"text-white/35 border border-transparent hover:text-white/70"}`}>{t}</button>)}</div>
  <div className="grid grid-cols-1 sm:grid-cols-3 gap-2.5 mb-5">{[{label:"Revenue",value:"$24,580",trend:"+12%",color:"#22C55E"},{label:"Expenses",value:"$8,340",trend:"—",color:"#8B92B0"},{label:"Net Profit",value:"$16,240",trend:"+19%",color:"#5B6EF5"}].map(s=><div key={s.label} className="relative overflow-hidden bg-[#0b1220]/90 border border-white/[.06] rounded-xl p-4 shadow-[0_12px_35px_rgba(0,0,0,.13)]"><div className="absolute right-0 top-0 w-24 h-24 bg-indigo-500/[.05] blur-3xl"/><p className="relative text-[8px] text-slate-500 mb-1">{s.label}</p><div className="relative flex items-baseline gap-2"><p className="text-xl font-semibold text-white">{s.value}</p>{s.trend!=="—"&&<span className="text-[8px]" style={{color:s.color}}>{s.trend}</span>}</div><div className="relative mt-3 h-1 rounded-full bg-white/[.035] overflow-hidden"><div className="h-full rounded-full" style={{width:s.label==="Revenue"?"72%":s.label==="Expenses"?"38%":"64%",background:s.color}}/></div></div>)}</div>
  <div className="grid lg:grid-cols-3 gap-2.5"><div className="lg:col-span-2 bg-[#0b1220]/90 border border-white/[.06] rounded-xl p-4 shadow-[0_16px_45px_rgba(0,0,0,.14)]"><div className="flex items-center justify-between mb-4"><div><h2 className="text-[11px] font-semibold text-white">Revenue vs Expenses</h2><p className="text-[7px] text-white/25 mt-1">Illustrative trend surface until live reporting aggregation is connected.</p></div><div className="flex gap-3 text-[8px]"><span className="flex items-center gap-1.5 text-slate-500"><span className="w-2 h-2 rounded-full bg-indigo-500"/>Revenue</span><span className="flex items-center gap-1.5 text-slate-500"><span className="w-2 h-2 rounded-full bg-violet-500"/>Expenses</span></div></div><svg viewBox="0 0 420 100" className="w-full h-28"><defs><linearGradient id="rrg2" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#5B6EF5" stopOpacity=".3"/><stop offset="100%" stopColor="#5B6EF5" stopOpacity="0"/></linearGradient><linearGradient id="eeg2" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#8B5CF6" stopOpacity=".2"/><stop offset="100%" stopColor="#8B5CF6" stopOpacity="0"/></linearGradient></defs>{[25,50,75].map(y=><line key={y} x1="0" y1={y} x2="420" y2={y} stroke="#232B4D" strokeWidth="1"/>)}<polygon points={`0,100 ${toPath(REV,420,100)} 420,100`} fill="url(#rrg2)"/><polyline points={toPath(REV,420,100)} fill="none" stroke="#5B6EF5" strokeWidth="2.5" strokeLinecap="round"/><polygon points={`0,100 ${toPath(EXP,420,100)} 420,100`} fill="url(#eeg2)"/><polyline points={toPath(EXP,420,100)} fill="none" stroke="#8B5CF6" strokeWidth="2" strokeLinecap="round"/>{MONTHS.map((m,i)=><text key={m} x={(i/(MONTHS.length-1))*420} y="99" fill="#6f7893" fontSize="9" textAnchor="middle">{m}</text>)}</svg></div>
  <div className="bg-[#0b1220]/90 border border-white/[.06] rounded-xl p-4 shadow-[0_16px_45px_rgba(0,0,0,.14)]"><h2 className="text-[11px] font-semibold text-white">Revenue by Source</h2><p className="text-[7px] text-white/25 mt-1 mb-3">Current reporting mix</p><div className="flex items-center gap-3"><DonutChart/><div className="space-y-2 flex-1">{DONUT.map(d=><div key={d.label} className="flex items-center gap-2"><span className="w-2 h-2 rounded-full shrink-0" style={{background:d.color}}/><span className="text-[8px] text-slate-500">{d.label}</span><span className="text-[8px] font-medium text-white ml-auto">{d.pct}%</span></div>)}</div></div></div></div>
  <div className="mt-2.5 grid sm:grid-cols-3 gap-2.5">{[["Customer health","Retention, invoice activity and relationship signals.","CRM"],["Inventory health","Stock velocity and low-stock monitoring.","OPS"],["Marketing health","Campaign, channel and conversion signals.","GROW"]].map(([t,d,b])=><div key={t} className="rounded-xl border border-white/[.055] bg-[#080e1a]/85 p-3.5"><div className="flex justify-between"><span className="text-[8px] uppercase tracking-[.15em] text-indigo-200/40">{b}</span><span className="text-[7px] text-white/15">→</span></div><p className="text-[9px] text-white/65 mt-2">{t}</p><p className="text-[7px] text-white/25 mt-1 leading-4">{d}</p></div>)}</div>
 </div></div>;
}
