"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";

type Wallet={id:string;name:string;wallet_type:string;currency:string;status:string;available_balance:number;pending_balance:number;ledger_balance:number;provider?:string|null};
type Tx={id:string;type:string;direction:string;status:string;amount:number;fee_amount:number;currency:string;counterparty_name?:string|null;description?:string|null;created_at:string};

export default function WalletPage(){
 const [wallets,setWallets]=useState<Wallet[]>([]),[txs,setTxs]=useState<Tx[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[tab,setTab]=useState<"overview"|"send"|"fund"|"history"|"tools">("overview");
 const [amount,setAmount]=useState(""),[walletId,setWalletId]=useState(""),[direction,setDirection]=useState<"deposit"|"withdrawal">("deposit"),[method,setMethod]=useState("bank_transfer");
 async function load(){setLoading(true); const r=await fetch("/api/wallet"); const d=await r.json(); if(r.ok){setWallets(d.wallets||[]);setTxs(d.transactions||[]);setWalletId(d.wallets?.[0]?.id||"")} else setMessage(d.error||"Unable to load wallet."); setLoading(false)}
 useEffect(()=>{load()},[]);
 const selected=wallets.find(w=>w.id===walletId)||wallets[0];
 const total=useMemo(()=>wallets.reduce((s,w)=>s+(Number(w.available_balance)||0),0),[wallets]);
 async function post(body:any){setMessage("");const r=await fetch("/api/wallet",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const d=await r.json();setMessage(r.ok?(d.providerAction?"Request created. "+d.providerAction+".":"Done."):(d.error||"Action failed."));if(r.ok)load()}
 async function createWallet(){const name=window.prompt("Wallet name","Operating Wallet");if(name)post({action:"create_wallet",name,currency:selected?.currency||"USD",hasExistingWallet:wallets.length>0})}
 if(loading)return <main className="min-h-screen bg-ledger p-8">Loading Wallet Center…</main>;
 return <main className="min-h-screen bg-ledger text-ink">
  <header className="border-b border-rule bg-white"><div className="max-w-7xl mx-auto px-6 py-5 flex justify-between"><div><Link href="/dashboard/money" className="text-xs text-ink/45">← Money Center</Link><h1 className="font-display text-3xl mt-1">Wallet Center</h1></div><button onClick={createWallet} className="bg-ink text-white px-4 py-2 text-sm">+ New wallet</button></div></header>
  <section className="max-w-7xl mx-auto px-6 py-8">
   {message&&<div className="mb-5 border border-rule bg-white px-4 py-3 text-sm">{message}</div>}
   <div className="grid lg:grid-cols-3 gap-5">
    <div className="lg:col-span-2 bg-ink text-mist p-7"><p className="text-xs uppercase tracking-[.18em] text-mist/45">Available across wallets</p><p className="font-display text-4xl mt-2">{selected?.currency||"USD"} {total.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}</p><div className="flex gap-3 mt-7 flex-wrap">{["Send","Receive","Deposit","Withdraw","History"].map(x=><button key={x} onClick={()=>setTab(x==="History"?"history":x==="Send"?"send":"fund")} className="border border-white/15 px-4 py-2 text-sm">{x}</button>)}</div></div>
    <div className="bg-white border border-rule p-6"><p className="text-xs uppercase tracking-[.18em] text-vault">Wallets</p><div className="mt-4 space-y-3">{wallets.map(w=><button onClick={()=>setWalletId(w.id)} key={w.id} className={"w-full text-left border p-4 "+(w.id===selected?.id?"border-vault":"border-rule")}><div className="flex justify-between"><span className="font-medium">{w.name}</span><span className="text-xs">{w.status}</span></div><p className="text-xs text-ink/45 mt-1">{w.wallet_type} · {w.currency}</p><p className="font-display text-xl mt-2">{Number(w.available_balance).toLocaleString(undefined,{minimumFractionDigits:2})}</p></button>)}{!wallets.length&&<button onClick={createWallet} className="w-full border border-dashed border-rule p-6 text-sm text-ink/50">Create your first wallet</button>}</div></div>
   </div>
   <nav className="flex gap-5 border-b border-rule mt-8">{[["overview","Overview"],["send","Send"],["fund","Deposit / Withdraw"],["history","Transactions"],["tools","Money tools"]].map(([k,v])=><button key={k} onClick={()=>setTab(k as any)} className={"py-3 text-sm "+(tab===k?"border-b-2 border-ink font-medium":"text-ink/45")}>{v}</button>)}</nav>
   {tab==="overview"&&<div className="grid md:grid-cols-3 gap-5 mt-6">{[
    ["Pay & transfer","Send to verified bank accounts, wallets, mobile-money destinations or internal wallets."],
    ["Receive money","Create provider-backed payment requests, deposit instructions and customer collection flows."],
    ["Protect money","Limits, approvals, 2FA gates, security events, dispute tracking and reversals."],
    ["Automate","Recurring transfers, scheduled payments, reserve allocations and payroll/tax buckets."],
    ["FX & multi-currency","Keep separate currency wallets and explicit conversion transactions with recorded rates."],
    ["Financial intelligence","Cash-flow forecasting, anomaly detection, reconciliation and AI explanations."]
   ].map(([a,b])=><div key={a} className="bg-white border border-rule p-6"><h3 className="font-display text-xl">{a}</h3><p className="text-sm text-ink/55 mt-2">{b}</p></div>)}</div>}
   {tab==="send"&&<div className="max-w-2xl bg-white border border-rule p-6 mt-6"><p className="text-xs uppercase tracking-[.16em] text-vault">Send money</p><h2 className="font-display text-2xl mt-2">Create a transfer request</h2><p className="text-sm text-ink/50 mt-2">BizStack records, validates and routes the request. A connected payment or banking provider executes the actual movement of funds.</p><div className="grid sm:grid-cols-2 gap-4 mt-6"><label className="text-sm">Wallet<select value={walletId} onChange={e=>setWalletId(e.target.value)} className="mt-1 w-full border border-rule p-2.5">{wallets.map(w=><option key={w.id} value={w.id}>{w.name} · {w.currency}</option>)}</select></label><label className="text-sm">Amount<input value={amount} onChange={e=>setAmount(e.target.value)} type="number" min="0.01" step="0.01" className="mt-1 w-full border border-rule p-2.5"/></label></div><button onClick={()=>post({action:"create_transfer",walletId,amount,currency:selected?.currency})} className="mt-5 bg-ink text-white px-5 py-2.5 text-sm">Create secure transfer request</button></div>}
   {tab==="fund"&&<div className="max-w-2xl bg-white border border-rule p-6 mt-6"><p className="text-xs uppercase tracking-[.16em] text-vault">Money movement</p><h2 className="font-display text-2xl mt-2">Deposit or withdraw</h2><div className="flex gap-2 mt-5">{["deposit","withdrawal"].map(x=><button key={x} onClick={()=>setDirection(x as "deposit"|"withdrawal")} className={"px-4 py-2 text-sm border "+(direction===x?"bg-ink text-white":"border-rule")}>{x==="deposit"?"Deposit":"Withdraw"}</button>)}</div><div className="grid sm:grid-cols-2 gap-4 mt-5"><label className="text-sm">Wallet<select value={walletId} onChange={e=>setWalletId(e.target.value)} className="mt-1 w-full border border-rule p-2.5">{wallets.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><label className="text-sm">Amount<input value={amount} onChange={e=>setAmount(e.target.value)} type="number" min="0.01" step="0.01" className="mt-1 w-full border border-rule p-2.5"/></label></div><label className="block text-sm mt-4">Method<select value={method} onChange={e=>setMethod(e.target.value)} className="mt-1 w-full border border-rule p-2.5"><option value="bank_transfer">Bank transfer</option><option value="card">Card</option><option value="mobile_money">Mobile money</option><option value="payment_processor">Payment processor</option><option value="cash">Cash</option><option value="internal_transfer">Internal transfer</option></select></label><button onClick={()=>post({action:"fund_wallet",walletId,amount,direction,method})} className="mt-5 bg-vault text-white px-5 py-2.5 text-sm">Create {direction} request</button></div>}
   {tab==="history"&&<div className="bg-white border border-rule mt-6"><div className="p-5 border-b border-rule"><h2 className="font-display text-xl">Transaction history</h2><p className="text-xs text-ink/45 mt-1">Every movement has a status, fee, provider reference and audit trail.</p></div><div className="divide-y divide-rule">{txs.map(t=><div key={t.id} className="p-5 flex justify-between gap-4"><div><p className="text-sm font-medium">{t.counterparty_name||t.description||t.type}</p><p className="text-xs text-ink/45 mt-1">{t.type} · {t.status} · {new Date(t.created_at).toLocaleString()}</p></div><div className="text-right"><p className="font-display">{t.direction==="credit"?"+":"-"}{t.currency} {Number(t.amount).toLocaleString()}</p><p className="text-xs text-ink/40">fee {Number(t.fee_amount||0).toLocaleString()}</p></div></div>)}{!txs.length&&<p className="p-8 text-sm text-ink/45">No wallet transactions yet.</p>}</div></div>}
   {tab==="tools"&&<div className="grid md:grid-cols-3 gap-5 mt-6">{["Beneficiaries & saved recipients","Scheduled & recurring payments","Reserves & tax buckets","FX conversion","Disputes & chargebacks","Statements & receipts","Payment links & collection","Cash deposit / withdrawal","Insurance & risk products","Business credit & financing","Supplier payments","Payroll & advances"].map(x=><div key={x} className="bg-white border border-rule p-5"><h3 className="font-display text-lg">{x}</h3><p className="text-xs text-ink/45 mt-2">Provider-ready module with its own data, permissions, status tracking and audit trail.</p></div>)}</div>}
  </section>
 </main>
}