"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { createClient } from "@/lib/supabase-browser";
import VoiceInput from "./voice-input";

type App={name:string;slug:string;category:string;description:string;icon_key:string;connected?:boolean;accounts?:any[]};
type Msg={id?:string;role:"user"|"assistant"|"tool";content:string;metadata?:any};
type Event={id:string;title:string;status:string;detail?:string;input?:any;output?:any};

const FALLBACK:App[]=[
 {name:"Google Drive",slug:"google-drive",category:"Files",description:"Search and work with Drive files, Docs, Sheets and Slides.",icon_key:"GD"},
 {name:"GitHub",slug:"github",category:"Developer",description:"Repositories, source, branches, issues and pull requests.",icon_key:"GH"},
 {name:"Gmail",slug:"gmail",category:"Communication",description:"Search, draft and send authorized business email.",icon_key:"GM"},
 {name:"Google Calendar",slug:"google-calendar",category:"Scheduling",description:"Availability and authorized events.",icon_key:"GC"},
 {name:"Slack",slug:"slack",category:"Communication",description:"Team conversations and authorized messages.",icon_key:"SL"},
 {name:"Notion",slug:"notion",category:"Knowledge",description:"Search selected workspace knowledge.",icon_key:"NO"},
 {name:"Supabase",slug:"supabase",category:"Infrastructure",description:"Authorized database and backend resources.",icon_key:"SB"},
 {name:"Vercel",slug:"vercel",category:"Deployment",description:"Projects, deployments and logs.",icon_key:"VC"},
 {name:"Custom Connector",slug:"custom-connector",category:"Custom",description:"Connect a documented API, webhook, database or private service.",icon_key:"+"}
];

export default function OperatorCockpit({businessId,businessName,initialConversationId,initialMessages}:{businessId:string;businessName:string;initialConversationId:string|null;initialMessages:Msg[]}){
 const db=createClient(),end=useRef<HTMLDivElement>(null);
 const [messages,setMessages]=useState(initialMessages),[input,setInput]=useState(""),[busy,setBusy]=useState(false);
 const [conversationId,setConversationId]=useState(initialConversationId),[events,setEvents]=useState<Event[]>([]);
 const [apps,setApps]=useState<App[]>(FALLBACK),[appOpen,setAppOpen]=useState(false),[query,setQuery]=useState("");
 const [context,setContext]=useState<App[]>([]),[tab,setTab]=useState("chat"),[selected,setSelected]=useState<Event|null>(null),[approval,setApproval]=useState<any>(null),[picker,setPicker]=useState(false);

 useEffect(()=>{end.current?.scrollIntoView({behavior:"smooth"})},[messages,busy]);
 useEffect(()=>{(async()=>{const [{data:c},{data:i}]=await Promise.all([db.from("ai_app_catalog").select("name,slug,category,description,icon_key,status").neq("status","private").order("sort_order"),db.from("integrations").select("id,provider,status,account_label,external_account_email,external_account_name").eq("business_id",businessId)]);const list=(c?.length?c:FALLBACK) as any[];setApps(list.map(a=>{const ac=(i||[]).filter((x:any)=>x.provider===a.slug&&x.status==="connected");return {...a,connected:ac.length>0,accounts:ac}}))})()},[businessId]);
 useEffect(()=>{const ch=db.channel("operator-cockpit-"+businessId).on("postgres_changes",{event:"*",schema:"public",table:"ai_agent_run_steps",filter:"business_id=eq."+businessId},p=>{const r:any=p.new;setEvents(v=>[{id:r.id,title:r.tool_key||r.step_type||"Operator step",status:r.status,detail:r.error_message,input:r.input,output:r.output},...v.filter(x=>x.id!==r.id)].slice(0,80))}).on("postgres_changes",{event:"*",schema:"public",table:"ai_build_steps",filter:"business_id=eq."+businessId},p=>{const r:any=p.new;setEvents(v=>[{id:r.id,title:r.step_key||"Build step",status:r.status,detail:r.error_message,input:r.input,output:r.output},...v.filter(x=>x.id!==r.id)].slice(0,80))}).subscribe();return()=>{db.removeChannel(ch)}},[businessId]);
 async function send(){const text=input.trim();if(!text||busy)return;setInput("");setBusy(true);setPicker(false);setMessages(v=>[...v,{role:"user",content:text,metadata:{apps:context.map(a=>a.slug)}}]);try{const r=await fetch("/api/assistant",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({input:text,conversationId,clientMessageId:crypto.randomUUID(),context:{apps:context.map(a=>a.slug)}})});const x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||"Operator request failed.");if(x.conversationId)setConversationId(x.conversationId);if(x.approval)setApproval(x.approval);setMessages(v=>[...v,{role:"assistant",content:x.message||"Done."}]);}catch(e){setMessages(v=>[...v,{role:"assistant",content:e instanceof Error?e.message:"The Operator could not complete that request."}])}finally{setBusy(false)}}
 async function connect(app:App){if(app.slug==="custom-connector"){location.href="/dashboard/integrations?custom=1";return}const r=await fetch("/api/apps/connect",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({app:app.slug})});const x=await r.json().catch(()=>({}));if(r.ok&&x.authorizationUrl)location.href=x.authorizationUrl;else setMessages(v=>[...v,{role:"assistant",content:x.error||"Connection could not be started."}])}
 const categories=useMemo(()=>["All",...Array.from(new Set(apps.map(a=>a.category)))],[apps]);
 const shown=useMemo(()=>apps.filter(a=>!query||a.name.toLowerCase().includes(query.toLowerCase())||a.description.toLowerCase().includes(query.toLowerCase())),[apps,query]);

 return <div className="rounded-[22px] border border-[#262a34] bg-[#0b0d10] text-white overflow-hidden shadow-[0_30px_100px_rgba(0,0,0,.25)]">
  <header className="h-14 px-4 border-b border-white/[.07] flex items-center justify-between"><div className="flex items-center gap-3"><div className="w-8 h-8 rounded-xl bg-white text-black flex items-center justify-center text-[9px] font-bold">BZ</div><div><div className="text-sm">Operator <span className="ml-1 text-[8px] text-emerald-300">LIVE</span></div><div className="text-[9px] text-white/30">{businessName}</div></div></div><button onClick={()=>setAppOpen(true)} className="rounded-lg bg-white/[.06] px-3 py-2 text-[10px]">Apps</button></header>
  <div className="px-4 py-2 border-b border-white/[.06] flex gap-2 overflow-x-auto"><span className="text-[8px] uppercase tracking-wider text-white/20 py-1">Context</span><span className="px-2 py-1 rounded bg-white/[.05] text-[9px] text-white/45">Business</span>{context.map(a=><button key={a.slug} onClick={()=>setContext(v=>v.filter(x=>x.slug!==a.slug))} className="px-2 py-1 rounded bg-indigo-400/10 text-[9px] text-indigo-200">@{a.name}</button>)}</div>
  <div className="grid xl:grid-cols-[390px_minmax(0,1fr)_260px] min-h-[780px]">
   <section className="bg-[#101217] border-r border-white/[.07] flex flex-col min-h-0">
    <nav className="h-10 px-3 border-b border-white/[.06] flex items-center gap-1">{["chat","code","preview","run","files"].map(x=><button key={x} onClick={()=>setTab(x)} className={tab===x?"px-2.5 py-1.5 rounded bg-white/[.08] text-[9px]":"px-2.5 py-1.5 text-white/30 text-[9px]"}>{x}</button>)}</nav>
    <div className="flex-1 overflow-y-auto">
     {tab==="chat"&&<div className="p-4 space-y-5">{!messages.length&&<div className="pt-8"><div className="text-[8px] uppercase tracking-[.2em] text-white/20">Autonomous workspace</div><h2 className="text-3xl mt-2 tracking-tight">What should I handle?</h2><p className="text-[11px] text-white/35 leading-5 mt-3">Tell the Operator the outcome. It chooses the route, connected tools and business context for you.</p><div className="grid grid-cols-2 gap-2 mt-5">{["Connect Google Drive","Find overdue invoices","Build a customer portal","Explain cash position"].map(x=><button key={x} onClick={()=>setInput(x)} className="text-left p-3 rounded-xl border border-white/[.07] text-[9px] text-white/45 hover:bg-white/[.04]">{x}</button>)}</div></div>}{messages.map((m,i)=><div key={m.id||i}><div className="text-[9px] text-white/25 mb-1">{m.role==="user"?"You":"Operator"}</div><div className="text-[12px] leading-6 text-white/70 whitespace-pre-wrap">{m.content}</div></div>)}{approval&&<div className="p-3 rounded-xl border border-amber-300/20 bg-amber-300/[.05]"><div className="text-[8px] text-amber-200 uppercase">Approval required</div><p className="text-[10px] mt-2">{approval.action}</p><button className="mt-3 bg-white text-black rounded-lg px-3 py-2 text-[9px]" onClick={async()=>{setBusy(true);const r=await fetch("/api/assistant/approve",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({runId:approval.runId})});const x=await r.json().catch(()=>({}));setApproval(x.approval||null);setMessages(v=>[...v,{role:"assistant",content:x.message||"Approved action completed."}]);setBusy(false)}}>Approve</button></div>}{busy&&<div className="text-[9px] text-white/30 animate-pulse">Operator is working across the workspace…</div>}<div ref={end}/></div>}
     {tab==="code"&&<Pane title="Code"><p>No fake code artifact is displayed. A real build will populate files, diffs and editable source here.</p></Pane>}
     {tab==="preview"&&<Pane title="Preview"><p>The executable preview attaches to the real project runtime when an artifact exists.</p></Pane>}
     {tab==="files"&&<Pane title="Files"><p>The workspace file graph will appear here as the Operator creates or attaches a project.</p></Pane>}
     {tab==="run"&&<div>{events.map(e=><button key={e.id} onClick={()=>setSelected(e)} className="w-full text-left px-4 py-3 border-b border-white/[.05] hover:bg-white/[.03]"><div className="flex gap-2 text-[9px]"><span className={e.status==="failed"?"text-red-300":"text-emerald-300"}>●</span><span className="text-white/55">{e.title}</span><span className="ml-auto text-white/20">{e.status}</span></div>{e.detail&&<p className="text-[8px] text-white/20 mt-1">{e.detail}</p>}</button>)}</div>}
    </div>
    <div className="p-3 border-t border-white/[.07]"><div className="rounded-2xl border border-white/[.1] bg-[#15181e] p-2">{picker&&<div className="mb-2 p-2 rounded-xl bg-[#1b1e25]">{apps.filter(a=>a.connected).map(a=><button key={a.slug} onClick={()=>{setContext(v=>v.some(x=>x.slug===a.slug)?v:[...v,a]);setPicker(false)}} className="block w-full text-left px-2 py-2 text-[9px] hover:bg-white/[.05]">@{a.name}</button>)}{!apps.some(a=>a.connected)&&<button onClick={()=>{setPicker(false);setAppOpen(true)}} className="text-[9px] text-indigo-200 p-2">Connect an app →</button>}</div>}<div className="flex items-end gap-2"><button onClick={()=>setPicker(v=>!v)} className="w-8 h-8 rounded-xl bg-white/[.05] text-white/40">+</button><VoiceInput onTranscript={setInput}/><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void send()}}} rows={2} placeholder="Ask the Operator to do something…" className="flex-1 resize-none bg-transparent outline-none text-[11px] leading-5 placeholder:text-white/20"/><button onClick={()=>void send()} disabled={!input.trim()||busy} className="w-9 h-9 rounded-xl bg-white text-black disabled:opacity-20">↑</button></div></div><p className="text-[8px] text-white/15 mt-2">Enter run · Shift+Enter newline · + adds connected tools to this turn</p></div>
   </section>
   <section className="bg-[#15181d] border-r border-white/[.07]"><div className="h-10 px-4 border-b border-white/[.06] flex items-center justify-between"><span className="text-[9px] text-white/35">Work surface</span><span className="text-[8px] text-white/20">agentic runtime</span></div><div className="h-[calc(100%-40px)] flex items-center justify-center p-10 text-center"><div className="max-w-md"><div className="w-16 h-16 rounded-[20px] border border-white/[.07] bg-white/[.03] mx-auto flex items-center justify-center text-[9px] text-white/20">SURFACE</div><h3 className="text-lg mt-5">The result lives here.</h3><p className="text-[10px] text-white/25 leading-5 mt-3">Preview, code, terminal, diffs and design become one continuous surface once the Operator has a real project artifact.</p></div></div></section>
   <aside className="bg-[#0f1115]"><div className="h-10 px-3 border-b border-white/[.06] flex items-center justify-between"><span className="text-[9px] text-white/45">Activity</span><span className="text-[8px] text-white/20">{events.length}</span></div><div className="max-h-[520px] overflow-y-auto">{events.slice(0,30).map(e=><button key={e.id} onClick={()=>setSelected(e)} className="w-full text-left px-3 py-2 hover:bg-white/[.03]"><div className="flex gap-2 text-[8px]"><span className="text-emerald-300">●</span><span className="text-white/45 truncate">{e.title}</span><span className="ml-auto text-white/15">{e.status}</span></div></button>)}</div><div className="border-t border-white/[.06] p-3"><div className="text-[8px] uppercase tracking-wider text-white/20">Connected accounts</div>{apps.filter(a=>a.connected).map(a=><div key={a.slug} className="mt-2 flex gap-2 items-center"><span className="w-5 h-5 rounded bg-white/[.05] flex items-center justify-center text-[7px]">{a.icon_key}</span><span className="text-[8px] text-white/45 truncate">{a.name}</span><span className="ml-auto text-emerald-300">●</span></div>)}</div></aside>
  </div>
  {selected&&<div className="fixed inset-0 z-50 bg-black/60 flex items-center justify-center p-4" onClick={()=>setSelected(null)}><div className="max-w-2xl w-full bg-[#171a20] border border-white/[.1] rounded-2xl p-4" onClick={e=>e.stopPropagation()}><div className="flex justify-between"><span className="text-xs">{selected.title}</span><button onClick={()=>setSelected(null)}>×</button></div><pre className="mt-4 text-[8px] text-white/50 whitespace-pre-wrap max-h-[60vh] overflow-auto">{JSON.stringify(selected,null,2)}</pre></div></div>}
  {appOpen&&<div className="fixed inset-0 z-50 bg-black/65 flex items-center justify-center p-4" onClick={()=>setAppOpen(false)}><div className="w-full max-w-5xl max-h-[88vh] overflow-hidden rounded-[22px] bg-[#12151a] border border-white/[.1]" onClick={e=>e.stopPropagation()}><div className="p-5 border-b border-white/[.07]"><div className="flex justify-between"><div><div className="text-[8px] uppercase tracking-[.2em] text-white/20">App directory</div><h3 className="text-xl mt-1">Connect your working world</h3><p className="text-[9px] text-white/30 mt-2">Accounts become available inside the Operator. Connect another account whenever you need a different workspace identity.</p></div><button onClick={()=>setAppOpen(false)}>×</button></div><div className="mt-4 flex gap-2"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search apps and capabilities…" className="flex-1 bg-white/[.04] border border-white/[.07] rounded-xl px-3 py-2.5 text-[10px] outline-none"/><button onClick={()=>location.href="/dashboard/integrations?custom=1"} className="bg-indigo-400/10 text-indigo-200 rounded-xl px-3 text-[9px]">+ Custom connector</button></div><div className="flex gap-1 mt-3">{categories.map(c=><span key={c} className="px-2 py-1 rounded bg-white/[.04] text-[8px] text-white/30">{c}</span>)}</div></div><div className="p-5 grid sm:grid-cols-2 lg:grid-cols-3 gap-2.5 overflow-y-auto max-h-[58vh]">{shown.map(a=><div key={a.slug} className="rounded-2xl border border-white/[.07] p-4 bg-white/[.015]"><div className="flex gap-3"><span className="w-9 h-9 rounded-xl bg-white/[.06] flex items-center justify-center text-[8px]">{a.icon_key}</span><div><p className="text-[10px]">{a.name}</p><p className="text-[8px] text-white/20 mt-1">{a.category}</p></div></div><p className="text-[9px] text-white/30 leading-4 mt-3 min-h-8">{a.description}</p>{a.connected&&a.accounts?.map((x:any)=><div key={x.id} className="mt-2 rounded-lg bg-emerald-300/[.04] border border-emerald-300/[.08] p-2"><p className="text-[8px] text-white/50 truncate">{x.account_label||x.external_account_email||"Connected account"}</p><p className="text-[7px] text-emerald-300/60">authorized</p></div>)}<div className="flex gap-1.5 mt-3"><button onClick={()=>void connect(a)} className="flex-1 rounded-lg bg-white/[.07] py-2 text-[8px]">{a.connected?"Connect another account":"Connect account"}</button>{a.connected&&<button onClick={()=>{setContext(v=>v.some(x=>x.slug===a.slug)?v:[...v,a]);setAppOpen(false)}} className="rounded-lg border border-white/[.07] px-2 text-[8px] text-indigo-200">Use</button>}</div></div>)}</div></div></div>}
 </div>;
}

function Pane({title,children}:{title:string;children:any}){return <div className="p-4"><div className="text-[9px] text-white/30 border-b border-white/[.06] pb-3">{title}</div><div className="text-[10px] text-white/25 leading-5 mt-4">{children}</div></div>}
