"use client";
import { useEffect, useState } from "react";

type Data={authenticated:boolean;portal?:any;customer?:any;invoices?:any[]};

export default function PortalClient({slug,initial}:{slug:string;initial:Data}){
 const [data,setData]=useState<Data>(initial),[email,setEmail]=useState(""),[token,setToken]=useState(""),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 useEffect(()=>{const t=new URLSearchParams(location.search).get("token");if(t){setToken(t);void verify(t)}},[]);
 async function verify(raw:string){
  setBusy(true);setNotice("");
  try{const r=await fetch("/api/portal/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token:raw})});const x=await r.json();if(!r.ok)throw new Error(x.error||"Access link failed.");const s=await fetch("/api/portal/session",{cache:"no-store"});setData(await s.json());history.replaceState({}, "", "/portal/"+encodeURIComponent(slug));}catch(e){setNotice(e instanceof Error?e.message:"Access verification failed.");}finally{setBusy(false)}
 }
 async function requestAccess(e:React.FormEvent){
  e.preventDefault();setBusy(true);setNotice("");
  try{const r=await fetch("/api/portal/request-access",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({slug,email})});const x=await r.json();if(!r.ok)throw new Error(x.error||"Could not request access.");setNotice(x.message||"Check your email for a secure access link.");}catch(e){setNotice(e instanceof Error?e.message:"Could not request access.");}finally{setBusy(false)}
 }
 async function logout(){await fetch("/api/portal/session",{method:"DELETE"});setData({authenticated:false});}
 if(!data.authenticated)return <main className="min-h-screen bg-[#f5f4ef] text-[#151515] flex items-center justify-center p-5"><div className="w-full max-w-md bg-white border border-black/10 rounded-3xl p-7 shadow-sm"><div className="text-[10px] uppercase tracking-[.2em] text-black/40">Customer portal</div><h1 className="text-2xl font-semibold mt-2">Secure customer access</h1><p className="text-sm text-black/50 leading-6 mt-3">Enter the email address your business uses for your customer account. We’ll send a one-time secure access link.</p><form onSubmit={requestAccess} className="mt-6 space-y-3"><input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" className="w-full rounded-xl border border-black/10 px-3 py-3 outline-none"/><button disabled={busy} className="w-full rounded-xl bg-[#151515] text-white py-3 text-sm disabled:opacity-40">{busy?"Sending…":"Send secure access link"}</button></form>{notice&&<p className="text-xs mt-4 text-black/55">{notice}</p>}</div></main>;
 const invoices=data.invoices||[];
 return <main className="min-h-screen bg-[#f5f4ef] text-[#151515]"><header className="border-b border-black/10 bg-white"><div className="max-w-6xl mx-auto px-5 py-5 flex items-center gap-4"><div><div className="text-[10px] uppercase tracking-[.2em] text-black/35">Customer portal</div><h1 className="text-xl font-semibold mt-1">{data.portal?.name||"Your account"}</h1></div><div className="ml-auto flex items-center gap-3"><span className="text-xs text-black/45">{data.customer?.email}</span><button onClick={logout} className="text-xs border border-black/10 rounded-lg px-3 py-2">Sign out</button></div></div></header><section className="max-w-6xl mx-auto p-5 md:p-8"><div className="grid md:grid-cols-3 gap-4"><div className="md:col-span-2 bg-white rounded-2xl border border-black/10 p-5"><div className="text-[10px] uppercase tracking-[.15em] text-black/35">Account</div><h2 className="text-lg font-semibold mt-2">{data.customer?.name}</h2><p className="text-sm text-black/45 mt-1">{data.customer?.company_name||data.customer?.phone||data.customer?.email}</p><div className="grid sm:grid-cols-3 gap-3 mt-6"><div className="rounded-xl bg-black/[.03] p-3"><div className="text-[9px] text-black/35">Invoices</div><div className="text-xl mt-1">{invoices.length}</div></div><div className="rounded-xl bg-black/[.03] p-3"><div className="text-[9px] text-black/35">Outstanding</div><div className="text-xl mt-1">{invoices.reduce((n,i)=>n+Math.max(Number(i.total||0)-Number(i.paid_amount||0),0),0).toFixed(2)} {data.customer?.preferred_currency||""}</div></div><div className="rounded-xl bg-black/[.03] p-3"><div className="text-[9px] text-black/35">Status</div><div className="text-sm mt-2">Active</div></div></div></div><div className="bg-[#151515] text-white rounded-2xl p-5"><div className="text-[9px] uppercase tracking-[.15em] text-white/40">Portal services</div><p className="text-sm text-white/70 leading-6 mt-3">Invoices, payment status, documents, orders, appointments and business messages can live here as the portal modules are enabled.</p></div></div><div className="mt-6 bg-white rounded-2xl border border-black/10 overflow-hidden"><div className="px-5 py-4 border-b border-black/10"><h2 className="font-semibold">Invoices</h2><p className="text-xs text-black/40 mt-1">Only records belonging to your customer account are shown.</p></div>{invoices.length?invoices.map(i=><div key={i.id} className="px-5 py-4 border-b border-black/5 flex items-center gap-4"><div><div className="text-sm font-medium">{i.invoice_number}</div><div className="text-xs text-black/40 mt-1">{i.issue_date} · due {i.due_date||"—"}</div></div><span className="ml-auto text-xs rounded-full bg-black/[.04] px-2 py-1">{i.status}</span><div className="text-sm font-medium">{Number(i.total||0).toFixed(2)} {i.currency}</div></div>):<div className="p-8 text-sm text-black/40">No invoices are available for this account yet.</div>}</div></section></main>;
}
