insert into public.ai_app_catalog
(slug,name,publisher,category,description,icon_key,auth_type,connection_mode,capabilities,scopes,status,sort_order)
values
('custom-api','Custom API','BizStack','Custom','Bring a documented REST or HTTP API into the Operator with governed authentication and actions.','API','custom','custom','["http","read","write","webhook"]','[]','active',1001),
('company-database','Company Database','BizStack','Data','Connect an authorized company database or controlled export as governed business context.','DB','database','database','["schema","read","query","sync"]','[]','active',1002),
('webhook-source','Webhook Source','BizStack','Automation','Create a signed inbound endpoint so external systems can trigger Operator workflows.','WH','webhook','custom','["events","webhooks","automation"]','[]','active',1003),
('bank-account','Bank Account','BizStack','Finance','Connect a supported financial-data provider or import verified bank activity for reconciliation.','BN','oauth','account','["balances","transactions","reconciliation"]','[]','active',1004),
('payment-processor','Payment Processor','BizStack','Payments','Connect collections, payouts, refunds and disputes through a supported provider.','PAY','oauth','account','["payments","payouts","refunds","disputes","webhooks"]','[]','active',1005),
('accounting-platform','Accounting Platform','BizStack','Accounting','Connect an accounting system and keep synchronization auditable and permission-aware.','ACC','oauth','company','["accounts","invoices","payments","contacts","sync"]','[]','active',1006)
on conflict (slug) do update set name=excluded.name,description=excluded.description,category=excluded.category,icon_key=excluded.icon_key,auth_type=excluded.auth_type,connection_mode=excluded.connection_mode,capabilities=excluded.capabilities,sort_order=excluded.sort_order;