import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase-server";

export default async function DashboardPage() {
 const supabase=createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user) redirect("/login");
 const {data:business}=await supabase.from("businesses").select("*").eq("owner_id",user.id).single(); if(!business) redirect("/onboarding");
 return <main className="min-h-screen bg-ledger"><header className="border-b border-rule bg-white"><div className="max-w-6xl mx-auto px-6 py-5 flex items-center justify-between">
  <div><p className="font-display text-lg text-ink">{business.name}</p><p className="text-xs text-ink/45">{business.industry} · {business.currency}</p></div>
  <nav className="hidden sm:flex items-center gap-1 text-sm"><Link href="/dashboard/customers" className="text-ink/65 hover:text-ink px-3 py-2">Customers</Link><Link href="/dashboard/invoices" className="text-ink/65 hover:text-ink px-3 py-2">Invoices</Link><Link href="/dashboard/money" className="text-ink/65 hover:text-ink px-3 py-2">Money</Link><Link href="/dashboard/integrations" className="text-ink/65 hover:text-ink px-3 py-2">Integrations</Link><Link href="/dashboard/website" className="text-ink/65 hover:text-ink px-3 py-2">Website</Link><Link href="/dashboard/actions" className="text-ink/65 hover:text-ink px-3 py-2">Action Center</Link><Link href="/dashboard/settings/automation" className="text-ink/65 hover:text-ink px-3 py-2">Automation</Link></nav>
  <form action="/auth/sign-out" method="post"><button className="text-sm text-ink/45 hover:text-ink px-3 py-2">Sign out</button></form>
 </div></header>
 <section className="max-w-6xl mx-auto px-6 py-16"><p className="text-xs uppercase tracking-[0.16em] text-vault font-medium mb-2">Business workspace</p><h1 className="font-display text-3xl text-ink mb-2">Your business at a glance.</h1><p className="text-ink/65 max-w-lg leading-relaxed">Customers, invoices, money, integrations and automation live here. The technical foundation stays underneath the product instead of in your way.</p>
 <div className="mt-10 grid sm:grid-cols-2 lg:grid-cols-4 gap-px bg-rule border border-rule max-w-5xl"><Link href="/dashboard/customers" className="bg-white p-6 hover:bg-mist transition-colors"><h3 className="font-display text-lg text-ink mb-1">Customers</h3><p className="text-sm text-ink/60">Relationships, contacts and money owed.</p></Link><Link href="/dashboard/invoices" className="bg-white p-6 hover:bg-mist transition-colors"><h3 className="font-display text-lg text-ink mb-1">Invoices</h3><p className="text-sm text-ink/60">Commercial records and payment status.</p></Link><Link href="/dashboard/money" className="bg-white p-6 hover:bg-mist transition-colors"><h3 className="font-display text-lg text-ink mb-1">Money</h3><p className="text-sm text-ink/60">Cash movement, receivables and reserves.</p></Link><Link href="/dashboard/integrations" className="bg-white p-6 hover:bg-mist transition-colors"><h3 className="font-display text-lg text-ink mb-1">Connections</h3><p className="text-sm text-ink/60">Connect banks, payment systems and business data later.</p></Link><Link href="/dashboard/website" className="bg-white p-6 hover:bg-mist transition-colors"><h3 className="font-display text-lg text-ink mb-1">Website</h3><p className="text-sm text-ink/60">Build and publish a business website when you are ready.</p></Link></div>
 </section></main>;
}